version: '3.8'


services:
  # 1/ Wordpress
  wp:
    build: 
        context: ./build/php-8-apache
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - mysql

  # 2/ Database
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  # 3/ Wp cli
  wp-cli:
    image: wordpress:cli
    env_file:
      - .env
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_HOST: ${DB_HOST}
    volumes:
      - ./www:/var/www/html
    depends_on:
      - wp
      - mysql

volumes:
  mysql:
  wp: